# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/chenliu/Projects/cv_utils

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/chenliu/Projects/cv_utils

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/chenliu/Projects/cv_utils/CMakeFiles /home/chenliu/Projects/cv_utils/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/chenliu/Projects/cv_utils/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cv_utils

# Build rule for target.
cv_utils: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cv_utils
.PHONY : cv_utils

# fast build rule for target.
cv_utils/fast:
	$(MAKE) -f CMakeFiles/cv_utils.dir/build.make CMakeFiles/cv_utils.dir/build
.PHONY : cv_utils/fast

CommonOperations.o: CommonOperations.cpp.o
.PHONY : CommonOperations.o

# target to build an object file
CommonOperations.cpp.o:
	$(MAKE) -f CMakeFiles/cv_utils.dir/build.make CMakeFiles/cv_utils.dir/CommonOperations.cpp.o
.PHONY : CommonOperations.cpp.o

CommonOperations.i: CommonOperations.cpp.i
.PHONY : CommonOperations.i

# target to preprocess a source file
CommonOperations.cpp.i:
	$(MAKE) -f CMakeFiles/cv_utils.dir/build.make CMakeFiles/cv_utils.dir/CommonOperations.cpp.i
.PHONY : CommonOperations.cpp.i

CommonOperations.s: CommonOperations.cpp.s
.PHONY : CommonOperations.s

# target to generate assembly for a file
CommonOperations.cpp.s:
	$(MAKE) -f CMakeFiles/cv_utils.dir/build.make CMakeFiles/cv_utils.dir/CommonOperations.cpp.s
.PHONY : CommonOperations.cpp.s

FusionSpaceSolver.o: FusionSpaceSolver.cpp.o
.PHONY : FusionSpaceSolver.o

# target to build an object file
FusionSpaceSolver.cpp.o:
	$(MAKE) -f CMakeFiles/cv_utils.dir/build.make CMakeFiles/cv_utils.dir/FusionSpaceSolver.cpp.o
.PHONY : FusionSpaceSolver.cpp.o

FusionSpaceSolver.i: FusionSpaceSolver.cpp.i
.PHONY : FusionSpaceSolver.i

# target to preprocess a source file
FusionSpaceSolver.cpp.i:
	$(MAKE) -f CMakeFiles/cv_utils.dir/build.make CMakeFiles/cv_utils.dir/FusionSpaceSolver.cpp.i
.PHONY : FusionSpaceSolver.cpp.i

FusionSpaceSolver.s: FusionSpaceSolver.cpp.s
.PHONY : FusionSpaceSolver.s

# target to generate assembly for a file
FusionSpaceSolver.cpp.s:
	$(MAKE) -f CMakeFiles/cv_utils.dir/build.make CMakeFiles/cv_utils.dir/FusionSpaceSolver.cpp.s
.PHONY : FusionSpaceSolver.cpp.s

GeometryCalculations.o: GeometryCalculations.cpp.o
.PHONY : GeometryCalculations.o

# target to build an object file
GeometryCalculations.cpp.o:
	$(MAKE) -f CMakeFiles/cv_utils.dir/build.make CMakeFiles/cv_utils.dir/GeometryCalculations.cpp.o
.PHONY : GeometryCalculations.cpp.o

GeometryCalculations.i: GeometryCalculations.cpp.i
.PHONY : GeometryCalculations.i

# target to preprocess a source file
GeometryCalculations.cpp.i:
	$(MAKE) -f CMakeFiles/cv_utils.dir/build.make CMakeFiles/cv_utils.dir/GeometryCalculations.cpp.i
.PHONY : GeometryCalculations.cpp.i

GeometryCalculations.s: GeometryCalculations.cpp.s
.PHONY : GeometryCalculations.s

# target to generate assembly for a file
GeometryCalculations.cpp.s:
	$(MAKE) -f CMakeFiles/cv_utils.dir/build.make CMakeFiles/cv_utils.dir/GeometryCalculations.cpp.s
.PHONY : GeometryCalculations.cpp.s

ImageCompletion.o: ImageCompletion.cpp.o
.PHONY : ImageCompletion.o

# target to build an object file
ImageCompletion.cpp.o:
	$(MAKE) -f CMakeFiles/cv_utils.dir/build.make CMakeFiles/cv_utils.dir/ImageCompletion.cpp.o
.PHONY : ImageCompletion.cpp.o

ImageCompletion.i: ImageCompletion.cpp.i
.PHONY : ImageCompletion.i

# target to preprocess a source file
ImageCompletion.cpp.i:
	$(MAKE) -f CMakeFiles/cv_utils.dir/build.make CMakeFiles/cv_utils.dir/ImageCompletion.cpp.i
.PHONY : ImageCompletion.cpp.i

ImageCompletion.s: ImageCompletion.cpp.s
.PHONY : ImageCompletion.s

# target to generate assembly for a file
ImageCompletion.cpp.s:
	$(MAKE) -f CMakeFiles/cv_utils.dir/build.make CMakeFiles/cv_utils.dir/ImageCompletion.cpp.s
.PHONY : ImageCompletion.cpp.s

ImageMask.o: ImageMask.cpp.o
.PHONY : ImageMask.o

# target to build an object file
ImageMask.cpp.o:
	$(MAKE) -f CMakeFiles/cv_utils.dir/build.make CMakeFiles/cv_utils.dir/ImageMask.cpp.o
.PHONY : ImageMask.cpp.o

ImageMask.i: ImageMask.cpp.i
.PHONY : ImageMask.i

# target to preprocess a source file
ImageMask.cpp.i:
	$(MAKE) -f CMakeFiles/cv_utils.dir/build.make CMakeFiles/cv_utils.dir/ImageMask.cpp.i
.PHONY : ImageMask.cpp.i

ImageMask.s: ImageMask.cpp.s
.PHONY : ImageMask.s

# target to generate assembly for a file
ImageMask.cpp.s:
	$(MAKE) -f CMakeFiles/cv_utils.dir/build.make CMakeFiles/cv_utils.dir/ImageMask.cpp.s
.PHONY : ImageMask.cpp.s

ImageOperations.o: ImageOperations.cpp.o
.PHONY : ImageOperations.o

# target to build an object file
ImageOperations.cpp.o:
	$(MAKE) -f CMakeFiles/cv_utils.dir/build.make CMakeFiles/cv_utils.dir/ImageOperations.cpp.o
.PHONY : ImageOperations.cpp.o

ImageOperations.i: ImageOperations.cpp.i
.PHONY : ImageOperations.i

# target to preprocess a source file
ImageOperations.cpp.i:
	$(MAKE) -f CMakeFiles/cv_utils.dir/build.make CMakeFiles/cv_utils.dir/ImageOperations.cpp.i
.PHONY : ImageOperations.cpp.i

ImageOperations.s: ImageOperations.cpp.s
.PHONY : ImageOperations.s

# target to generate assembly for a file
ImageOperations.cpp.s:
	$(MAKE) -f CMakeFiles/cv_utils.dir/build.make CMakeFiles/cv_utils.dir/ImageOperations.cpp.s
.PHONY : ImageOperations.cpp.s

MatrixOperations.o: MatrixOperations.cpp.o
.PHONY : MatrixOperations.o

# target to build an object file
MatrixOperations.cpp.o:
	$(MAKE) -f CMakeFiles/cv_utils.dir/build.make CMakeFiles/cv_utils.dir/MatrixOperations.cpp.o
.PHONY : MatrixOperations.cpp.o

MatrixOperations.i: MatrixOperations.cpp.i
.PHONY : MatrixOperations.i

# target to preprocess a source file
MatrixOperations.cpp.i:
	$(MAKE) -f CMakeFiles/cv_utils.dir/build.make CMakeFiles/cv_utils.dir/MatrixOperations.cpp.i
.PHONY : MatrixOperations.cpp.i

MatrixOperations.s: MatrixOperations.cpp.s
.PHONY : MatrixOperations.s

# target to generate assembly for a file
MatrixOperations.cpp.s:
	$(MAKE) -f CMakeFiles/cv_utils.dir/build.make CMakeFiles/cv_utils.dir/MatrixOperations.cpp.s
.PHONY : MatrixOperations.cpp.s

PointCloudOperations.o: PointCloudOperations.cpp.o
.PHONY : PointCloudOperations.o

# target to build an object file
PointCloudOperations.cpp.o:
	$(MAKE) -f CMakeFiles/cv_utils.dir/build.make CMakeFiles/cv_utils.dir/PointCloudOperations.cpp.o
.PHONY : PointCloudOperations.cpp.o

PointCloudOperations.i: PointCloudOperations.cpp.i
.PHONY : PointCloudOperations.i

# target to preprocess a source file
PointCloudOperations.cpp.i:
	$(MAKE) -f CMakeFiles/cv_utils.dir/build.make CMakeFiles/cv_utils.dir/PointCloudOperations.cpp.i
.PHONY : PointCloudOperations.cpp.i

PointCloudOperations.s: PointCloudOperations.cpp.s
.PHONY : PointCloudOperations.s

# target to generate assembly for a file
PointCloudOperations.cpp.s:
	$(MAKE) -f CMakeFiles/cv_utils.dir/build.make CMakeFiles/cv_utils.dir/PointCloudOperations.cpp.s
.PHONY : PointCloudOperations.cpp.s

StatisticsCalculations.o: StatisticsCalculations.cpp.o
.PHONY : StatisticsCalculations.o

# target to build an object file
StatisticsCalculations.cpp.o:
	$(MAKE) -f CMakeFiles/cv_utils.dir/build.make CMakeFiles/cv_utils.dir/StatisticsCalculations.cpp.o
.PHONY : StatisticsCalculations.cpp.o

StatisticsCalculations.i: StatisticsCalculations.cpp.i
.PHONY : StatisticsCalculations.i

# target to preprocess a source file
StatisticsCalculations.cpp.i:
	$(MAKE) -f CMakeFiles/cv_utils.dir/build.make CMakeFiles/cv_utils.dir/StatisticsCalculations.cpp.i
.PHONY : StatisticsCalculations.cpp.i

StatisticsCalculations.s: StatisticsCalculations.cpp.s
.PHONY : StatisticsCalculations.s

# target to generate assembly for a file
StatisticsCalculations.cpp.s:
	$(MAKE) -f CMakeFiles/cv_utils.dir/build.make CMakeFiles/cv_utils.dir/StatisticsCalculations.cpp.s
.PHONY : StatisticsCalculations.cpp.s

TRW_S/errorFn.o: TRW_S/errorFn.cpp.o
.PHONY : TRW_S/errorFn.o

# target to build an object file
TRW_S/errorFn.cpp.o:
	$(MAKE) -f CMakeFiles/cv_utils.dir/build.make CMakeFiles/cv_utils.dir/TRW_S/errorFn.cpp.o
.PHONY : TRW_S/errorFn.cpp.o

TRW_S/errorFn.i: TRW_S/errorFn.cpp.i
.PHONY : TRW_S/errorFn.i

# target to preprocess a source file
TRW_S/errorFn.cpp.i:
	$(MAKE) -f CMakeFiles/cv_utils.dir/build.make CMakeFiles/cv_utils.dir/TRW_S/errorFn.cpp.i
.PHONY : TRW_S/errorFn.cpp.i

TRW_S/errorFn.s: TRW_S/errorFn.cpp.s
.PHONY : TRW_S/errorFn.s

# target to generate assembly for a file
TRW_S/errorFn.cpp.s:
	$(MAKE) -f CMakeFiles/cv_utils.dir/build.make CMakeFiles/cv_utils.dir/TRW_S/errorFn.cpp.s
.PHONY : TRW_S/errorFn.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... cv_utils"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... CommonOperations.o"
	@echo "... CommonOperations.i"
	@echo "... CommonOperations.s"
	@echo "... FusionSpaceSolver.o"
	@echo "... FusionSpaceSolver.i"
	@echo "... FusionSpaceSolver.s"
	@echo "... GeometryCalculations.o"
	@echo "... GeometryCalculations.i"
	@echo "... GeometryCalculations.s"
	@echo "... ImageCompletion.o"
	@echo "... ImageCompletion.i"
	@echo "... ImageCompletion.s"
	@echo "... ImageMask.o"
	@echo "... ImageMask.i"
	@echo "... ImageMask.s"
	@echo "... ImageOperations.o"
	@echo "... ImageOperations.i"
	@echo "... ImageOperations.s"
	@echo "... MatrixOperations.o"
	@echo "... MatrixOperations.i"
	@echo "... MatrixOperations.s"
	@echo "... PointCloudOperations.o"
	@echo "... PointCloudOperations.i"
	@echo "... PointCloudOperations.s"
	@echo "... StatisticsCalculations.o"
	@echo "... StatisticsCalculations.i"
	@echo "... StatisticsCalculations.s"
	@echo "... TRW_S/errorFn.o"
	@echo "... TRW_S/errorFn.i"
	@echo "... TRW_S/errorFn.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

